Repository SzFMV2021-Tavasz/AutomatedCar-A, pull requests merged in 2021-03, with the labels that each got.

#16 Added world serialization to- and from json files
  BaseModel/BaseModel.csproj
  BaseModel/JSONWorldSerializer.cs
  BaseModel/JsonHelper/WorldConverter.cs
  BaseModel/JsonHelper/WorldObjectJsonConverter.cs
  BaseModel/World.cs
  BaseModel/WorldObjects/WorldObject.cs
  BaseModel/app.config
  BaseModel/packages.config
  test/BaseModelTest/SerializingDummies/test_world.json
  test/BaseModelTest/SerializingDummies/test_world_1kmx1km.json
  test/BaseModelTest/SerializingTest.cs
Labels: status: in progress

#57 A1 sprint1 input handling
  src/AutomatedCar/KeyboardHandling/HoldableKey.cs
  src/AutomatedCar/KeyboardHandling/KeyboardHandler.cs
  src/AutomatedCar/KeyboardHandling/PressableKey.cs
  src/AutomatedCar/MainWindow.xaml.cs
  test/AutomatedCarTest/KeyboardHandling/KeyboardHandlerTest.cs
Labels: modul: HMI

#48 A1 rpm speed gauge
  src/AutomatedCar/AutomatedCar.csproj
  src/AutomatedCar/MainWindow.xaml.cs
  src/AutomatedCar/Models/RenderableWorldObject.cs
  src/AutomatedCar/ViewModels/DashboardViewModel.cs
  src/AutomatedCar/ViewModels/GaugeViewModelBase.cs
  src/AutomatedCar/ViewModels/RpmGaugeViewModel.cs
  src/AutomatedCar/ViewModels/SpeedGaugeViewModel.cs
  src/AutomatedCar/Views/ControlledCarInfos.xaml
  src/AutomatedCar/Views/ControlledCarInfos.xaml.cs
  src/AutomatedCar/Views/DashboardView.xaml
  src/AutomatedCar/Views/RpmGauge.xaml
  src/AutomatedCar/Views/RpmGauge.xaml.cs
  src/AutomatedCar/Views/SpeedGauge.xaml
  src/AutomatedCar/Views/SpeedGauge.xaml.cs
Labels: modul: HMI

#68 WorldRenderer element létrehozása, bekötése
  src/AutomatedCar/AutomatedCar.csproj
  src/AutomatedCar/MainWindow.xaml.cs
  src/AutomatedCar/ViewModels/CourseDisplayViewModel.cs
  src/AutomatedCar/Views/CourseDisplayView.xaml
  src/AutomatedCar/Visualization/WorldObjectTransformer.cs
  src/AutomatedCar/Visualization/WorldRenderer.cs
  test/BaseModelTest/BaseModelTest.csproj
Labels: modul: visualization

#77 A1 transmission and indicator
  src/AutomatedCar/Assets/arrow.png
  src/AutomatedCar/AutomatedCar.csproj
  src/AutomatedCar/Models/Enums/Gear.cs
  src/AutomatedCar/ViewModels/DashboardViewModel.cs
  src/AutomatedCar/ViewModels/LeftTurnSignalViewModel.cs
  src/AutomatedCar/ViewModels/RightTurnSignalViewModel.cs
  src/AutomatedCar/ViewModels/TransmissionViewModel.cs
  src/AutomatedCar/ViewModels/TurnSignalViewModelBase.cs
  src/AutomatedCar/Views/DashboardView.xaml
  src/AutomatedCar/Views/LeftTurnSignal.xaml
  src/AutomatedCar/Views/LeftTurnSignal.xaml.cs
  src/AutomatedCar/Views/RightTurnSignal.xaml
  src/AutomatedCar/Views/RightTurnSignal.xaml.cs
  src/AutomatedCar/Views/RpmGauge.xaml
  src/AutomatedCar/Views/SpeedGauge.xaml
  src/AutomatedCar/Views/Transmission.xaml
  src/AutomatedCar/Views/Transmission.xaml.cs
  src/BaseModel/BaseModel.csproj.orig
Labels: modul: HMI

#71 A1 sprint1 gas pedal progressbar
  src/AutomatedCar/ViewModels/DashboardViewModel.cs
  src/AutomatedCar/ViewModels/GasPedalViewModel.cs
  src/AutomatedCar/Views/DashboardView.xaml
  src/AutomatedCar/Views/GasPedal.xaml
  src/AutomatedCar/Views/GasPedal.xaml.cs
Labels: modul: HMI

#70 Vonóerő és fékezési erő
  src/AutomatedCar/SystemComponents/Powertrain/IVehicleConstants.cs
  src/AutomatedCar/SystemComponents/Powertrain/IVehicleForces.cs
  src/AutomatedCar/SystemComponents/Powertrain/VehicleForces.cs
  test/AutomatedCarTest/SystemComponents/Powertrain/VehicleForcesTests.cs
Labels: modul: powertrain

#72 A1 sprint1 brake pedal progressbar
  src/AutomatedCar/ViewModels/BreakPedalViewModel.cs
  src/AutomatedCar/ViewModels/DashboardViewModel.cs
  src/AutomatedCar/Views/BreakPedal.xaml
  src/AutomatedCar/Views/BreakPedal.xaml.cs
  src/AutomatedCar/Views/DashboardView.xaml
Labels: modul: HMI

#74 Vizualiáció során használt kamera
  src/AutomatedCar/Models/IRenderableWorldObject.cs
  src/AutomatedCar/Models/RenderableWorldObject.cs
  src/AutomatedCar/Visualization/RenderCamera.cs
  src/AutomatedCar/Visualization/WorldObjectTransformer.cs
  src/AutomatedCar/Visualization/WorldRenderer.cs
  test/AutomatedCarTest/AutomatedCarTest.csproj
  test/AutomatedCarTest/Visualization/RenderCameraTests.cs
Labels: modul: visualization

#81 Jármű fizika integrátor
  src/AutomatedCar/SystemComponents/Powertrain/IIntegrator.cs
  src/AutomatedCar/SystemComponents/Powertrain/IVehicleForces.cs
  src/AutomatedCar/SystemComponents/Powertrain/Integrator.cs
  src/AutomatedCar/SystemComponents/Powertrain/ParticleIntegrator.cs
  src/AutomatedCar/SystemComponents/Powertrain/VehicleConstants.cs
  src/AutomatedCar/SystemComponents/Powertrain/VehicleForces.cs
  src/AutomatedCar/SystemComponents/Powertrain/VehicleTransform.cs
  src/AutomatedCar/SystemComponents/Powertrain/WheelKind.cs
  test/AutomatedCarTest/SystemComponents/Powertrain/IntegratorTests.cs
  test/AutomatedCarTest/SystemComponents/Powertrain/ParticleIntegratorTests.cs
  test/AutomatedCarTest/SystemComponents/Powertrain/VehicleForcesTests.cs
Labels: modul: powertrain

#83 A1 - car info & last sign
  src/AutomatedCar/AutomatedCar.csproj
  src/AutomatedCar/ViewModels/CarInfoViewModel.cs
  src/AutomatedCar/ViewModels/DashboardViewModel.cs
  src/AutomatedCar/ViewModels/LastSignViewModel.cs
  src/AutomatedCar/Views/CarInfoView.xaml
  src/AutomatedCar/Views/CarInfoView.xaml.cs
  src/AutomatedCar/Views/ControlledCarInfos.xaml
  src/AutomatedCar/Views/DashboardView.xaml
  src/AutomatedCar/Views/LastSignView.xaml
  src/AutomatedCar/Views/LastSignView.xaml.cs
Labels: modul: HMI

#86 Priority checker a3
  src/AutomatedCar/SystemComponents/Packets/IReadOnlyACCPacket.cs
  src/AutomatedCar/SystemComponents/Packets/IReadOnlyAEBPacket.cs
  src/AutomatedCar/SystemComponents/Packets/IReadOnlyHMIPacket.cs
  src/AutomatedCar/SystemComponents/Packets/IReadOnlyLKAPacket.cs
  src/AutomatedCar/SystemComponents/Packets/IReadOnlyPPPacket.cs
  src/AutomatedCar/SystemComponents/Powertrain/IPriorityChecker.cs
  src/AutomatedCar/SystemComponents/Powertrain/PacketEnum.cs
  src/AutomatedCar/SystemComponents/Powertrain/PowertrainComponent.cs
  src/AutomatedCar/SystemComponents/Powertrain/PriorityChecker.cs
  src/AutomatedCar/SystemComponents/VirtualFunctionBus.cs
  test/AutomatedCarTest/SystemComponents/Powertrain/PowertrainComponentTests.cs
Labels: modul: powertrain

#88 BaseModel.World benyomása a skeletonbe
  src/AutomatedCar/MainWindow.xaml.cs
  src/AutomatedCar/Models/RenderableWorldObject.cs
  src/AutomatedCar/Models/World.cs
  src/AutomatedCar/Visualization/RenderCamera.cs
  src/AutomatedCar/Visualization/WorldObjectTransformer.cs
  src/AutomatedCar/Visualization/WorldRenderer.cs
  src/BaseModel/Bandaid/IRenderableWorldObject.cs
  src/BaseModel/WorldObjects/WorldObject.cs
  test/AutomatedCarTest/Visualization/RenderCameraTests.cs
Labels: modul: visualization

#93 A1 sprint1 car control
  src/AutomatedCar/MainWindow.xaml.cs
  src/AutomatedCar/ViewModels/DashboardViewModel.cs
  src/AutomatedCar/ViewModels/SteeringWheelViewModel.cs
Labels: modul: HMI

#85 A1 sprint1 sequential transmission
  src/AutomatedCar/Converters/GearEnumToStringConverter.cs
  src/AutomatedCar/MainWindow.xaml.cs
  src/AutomatedCar/ViewModels/DashboardViewModel.cs
  src/AutomatedCar/ViewModels/TransmissionViewModel.cs
  src/AutomatedCar/Views/Transmission.xaml
  test/AutomatedCarTest/ViewModels/TransmissionViewModelTests.cs
Labels: modul: HMI

#98 A1 sprint1 hmi packets
  src/AutomatedCar/MainWindow.xaml.cs
  src/AutomatedCar/SystemComponents/Packets/HMIPacket.cs
  src/AutomatedCar/ViewModels/DashboardViewModel.cs
  test/AutomatedCarTest/SystemComponents/Packets/HMIPacketTest.cs
Labels: modul: HMI

#102 Fix #99
  src/AutomatedCar/ViewModels/DashboardViewModel.cs
Labels: modul: HMI

#103 Add bindings to sequential shifting and turning indicators on
  src/AutomatedCar/MainWindow.xaml.cs
Labels: effort: low, modul: HMI

#101 A4 Rotation, Sensors
  src/AutomatedCar/MainWindow.xaml.cs
  src/AutomatedCar/Models/AutomatedCar.cs
  src/AutomatedCar/Models/RenderableWorldObject.cs
  src/AutomatedCar/Visualization/RenderCamera.cs
  src/AutomatedCar/Visualization/WorldObjectTransformer.cs
  src/AutomatedCar/Visualization/WorldRenderer.cs
  src/BaseModel/Bandaid/IRenderableWorldObject.cs
  src/BaseModel/WorldObjects/WorldObject.cs
  test/AutomatedCarTest/Visualization/RenderCameraTests.cs
Labels: modul: visualization

#100 Car updater a3
  src/AutomatedCar/MainWindow.xaml.cs
  src/AutomatedCar/Models/AutomatedCar.cs
  src/AutomatedCar/SystemComponents/Packets/PowertrainComponentPacket.cs
  src/AutomatedCar/SystemComponents/Powertrain/CarUpdater.cs
  src/AutomatedCar/SystemComponents/Powertrain/ICarUpdater.cs
  src/AutomatedCar/SystemComponents/Powertrain/ITransmission.cs
  src/AutomatedCar/SystemComponents/Powertrain/PowertrainComponent.cs
  src/AutomatedCar/SystemComponents/Powertrain/PriorityChecker.cs
  src/AutomatedCar/SystemComponents/Powertrain/Transmission.cs
  test/AutomatedCarTest/SystemComponents/Powertrain/CarUpdaterTests.cs
  test/AutomatedCarTest/SystemComponents/Powertrain/PowertrainComponentTests.cs
Labels: modul: powertrain

#108 Stop tábla kép fix
  src/AutomatedCar/AutomatedCar.csproj
Labels: type: bug

#117 RenderCamera javítások
  src/AutomatedCar/Visualization/RenderCamera.cs
  src/AutomatedCar/Visualization/WorldRenderer.cs
  test/AutomatedCarTest/Visualization/RenderCameraTests.cs
Labels: modul: visualization

#119 Jármű mozgatásával kapcsolatos bugfixek
  src/AutomatedCar/SystemComponents/Powertrain/CarUpdater.cs
  src/AutomatedCar/SystemComponents/Powertrain/IIntegrator.cs
  src/AutomatedCar/SystemComponents/Powertrain/IVehicleForces.cs
  src/AutomatedCar/SystemComponents/Powertrain/Integrator.cs
  src/AutomatedCar/SystemComponents/Powertrain/MathExtensions.cs
  src/AutomatedCar/SystemComponents/Powertrain/ParticleIntegrator.cs
  src/AutomatedCar/SystemComponents/Powertrain/PowertrainComponent.cs
  src/AutomatedCar/SystemComponents/Powertrain/ReverseMovement.cs
  src/AutomatedCar/SystemComponents/Powertrain/Transmission.cs
  src/AutomatedCar/SystemComponents/Powertrain/VehicleForces.cs
  test/AutomatedCarTest/SystemComponents/Powertrain/CarUpdaterTests.cs
  test/AutomatedCarTest/SystemComponents/Powertrain/IntegratorTests.cs
  test/AutomatedCarTest/SystemComponents/Powertrain/ParticleIntegratorTests.cs
  test/AutomatedCarTest/SystemComponents/Powertrain/ReverseMovementTests.cs
Labels: modul: powertrain
